const extraResources = {
  "pt": {
    translation: {
      "title": "Estação Ferroviária de Pljevlja",
      "naslov": "A ESTAÇÃO FERROVIÁRIA \"PLJEVLJA\" NÃO EXISTE, ISTO É UM EXERCÍCIO DE PROGRAMAÇÃO!",
      "podnaslov": "Bem-vindo à página oficial!",
      "footer": "&copy; 20__ Estação Ferroviária de Pljevlja",
      "navNaslovna": "Início",
      "navKontakt": "Contato",
      "navVozniRed": "Horário",
      "navGalerija": "Galeria",
      "navInformacije": "Informações",
      "navOpsteInformacije": "Informações gerais",
      "navFAQ": "Perguntas frequentes",
      "navIstorija": "História",
      "p1": "Bem-vindo à página oficial da Estação Ferroviária de Pljevlja!",
      "p2": "Aqui você encontra todas as informações sobre horários, contatos e galeria de fotos.",
      "p3": "Para mais informações, selecione uma opção no menu.",
      "p4": "Obrigado por visitar nosso site!",
      "p5": "Se tiver dúvidas ou sugestões, entre em contato.",
      "p6": "Atenciosamente,",
      "p7": "Estação Ferroviária de Pljevlja",
      "kontaktNaslov": "Contato",
      "kontaktInfo": "Informações de contato",
      "adresa": "Endereço: Estação Ferroviária de Pljevlja, Pljevlja, Montenegro",
      "telefon": "Telefone: +382 555666555",
      "email": "E-mail: info@zeljeznickastanicapljevlja.me",
      "posaljitePoruku": "Enviar mensagem",
      "lblIme": "Nome:",
      "lblPrezime": "Sobrenome:",
      "lblEmail": "E-mail:",
      "lblPoruka": "Mensagem:",
      "btnPosalji": "Enviar",
      "ime": "Nome",
      "prezime": "Sobrenome",
      "poruka": "Mensagem",
      "adresaLabel": "Endereço:",
      "telefonLabel": "Telefone:",
      "emailLabel": "E-mail:",
      "radnoVremeLabel": "Horário de funcionamento:",
      "radnoVremeVrednost": "07:00 – 20:00 (segunda–domingo)",
      "galerijaNaslov": "Galeria das estações ferroviárias",
      "opis1": "Estação de Podgorica (2013)",
      "opis2": "Estação de Bar (2013)",
      "opis3": "Estação de Bar (2019)",
      "opis4": "Estação de Podgorica (2019)",
      "opis5": "Plataformas da estação de Bar",
      "alt1": "Estação de Podgorica",
      "alt2": "Estação de Bar",
      "alt3": "Estação de Bar 2019",
      "alt4": "Estação de Podgorica 2019",
      "alt5": "Plataformas da estação de Bar",
      "informacijeNaslov": "Informações",
      "nemaVozova": "Atualmente não há trens.",
      "pretrazi": "Pesquisar",
      "datum": "Data",
      "polazak": "Partida",
      "dolazak": "Chegada",
      "od": "De",
      "ka": "Para",
      "prevoznik": "Transportadora",
      "tipKarte": "Tipo de bilhete",
      "rezervacija": "Reserva",
      "placanje": "Pagamento",
      "student": "Desconto estudante",
      "penzioner": "Desconto aposentado",
      "cena": "Preço",
      "napomena": "Observação",
      "lblOd": "De:",
      "lblKa": "Para:",
      "lblDatum": "Data:",
      "btnPretrazi": "Pesquisar",
      "thDatum": "Data",
      "thPolazak": "Partida",
      "thDolazak": "Chegada",
      "thOd": "De",
      "thKa": "Para",
      "thPrevoznik": "Transportadora",
      "thTipKarte": "Tipo de bilhete",
      "thRezervacija": "Reserva",
      "thPlacanje": "Pagamento",
      "thStudent": "Desconto estudante",
      "thPenzioner": "Desconto aposentado",
      "thCena": "Preço",
      "thNapomena": "Observação",
      "thSlobodnaMjesta": "Lugares livres",
      "thRezervisanoMjesta": "Lugares reservados",
      "thUkupnoMjesta": "Total de lugares",
      "thCijenaKarte": "Preço do bilhete",
      "thTipVoznje": "Tipo de viagem",
      "thVoz": "Trem",
      "thVozniRed": "Horário",
      "thVozniRedDatum": "Data",
      "thVozniRedVrijeme": "Hora",
      "thVozniRedPolazak": "Partida",
      "thVozniRedDolazak": "Chegada",
      "thVozniRedOd": "De",
      "thVozniRedKa": "Para",
      "thVozniRedPrevoznik": "Transportadora",
      "thVozniRedTipKarte": "Tipo de bilhete",
      "thVozniRedRezervacija": "Reserva",
      "thVozniRedPlacanje": "Pagamento",
      "thVozniRedStudent": "Desconto estudante",
      "thVozniRedPenzioner": "Desconto aposentado",
      "thVozniRedCena": "Preço",
      "thVozniRedNapomena": "Observação",
      "placanje_online": "Pagamento online",
      "placanje_gotovina": "Pagamento em dinheiro",
      "placanje_kartica": "Pagamento com cartão",
      "placanje_PayPal": "Pagamento via PayPal",
      "placanjeStripe": "Stripe",
      "placanjeOnline": "Pagamento online",
      "Pređи_na_plaćanje": "Ir para o pagamento",
      "Kupi_kartu": "Comprar bilhete",
      "Ipak_ne": "Ainda não.",
      "uplatnaForma": "Formulário de pagamento",
      "sql_modal": "Escolha o método de pagamento:",
      "Izaberite_način_plaćanja": "Escolha o método de pagamento:",
      "kupovinaNijeDostupna": "A compra online não está disponível para esta partida. Contate a estação para mais informações.",
      "nijeIzabranPolazak": "Partida não selecionada.",
      "nema_podataka": "Sem dados",
      "closeModal": "Ainda não!",
      "broj_telefona": "Número de telefone",
      "email_adresa": "Endereço de e-mail",
      "adresa_stanice": "Endereço da estação",
      "radno_vrijeme": "Horário de funcionamento",
      "radno_vrijeme_vrijednost": "07:00 – 20:00 (segunda–domingo)",
      "brojSlobodnihMjesta": "Número de lugares livres",
      "detaljiPolaska": "Detalhes da partida",
      "naslovTab": "Horário",
      "rezervacija_da": "Sim",
      "rezervacija_ne": "Não",
      "footerZvanicniLinkovi": "Links oficiais",
      "footerLinkZCG": "Transporte Ferroviário de Montenegro",
      "footerLinkZICG": "Infraestrutura Ferroviária de Montenegro",
      "footerLinkVlada": "Governo de Montenegro",
      "footerLinkOpština": "Município de Pljevlja",
      "footerLinkTOP": "Organização Turística de Pljevlja",
      "footerLinkJUCKPV": "Centro Cultural de Pljevlja",
      "footerDrustveneMreze": "Redes sociais",
      "footerFacebook": "Facebook",
      "footerInstagram": "Instagram",
      "footerTwitter": "Twitter",
      "footerQRNaslov": "Código QR",
      "footerQROpis": "Escaneie o código QR para acesso rápido aos nossos serviços e informações.",
      "footerQRAlt": "Código QR da Estação de Pljevlja",
      "faqNaslovTab": "Perguntas frequentes",
      "faqNaslov": "Perguntas frequentes (FAQ)",
      "faqPitanje1": "É possível comprar bilhete online?",
      "faqOdgovor1": "Atualmente não é possível comprar bilhete online pois a estação ainda não foi construída.",
      "faqPitanje2": "Onde posso obter mais informações sobre partidas?",
      "faqOdgovor2": "Todas as informações estarão disponíveis neste site quando a estação estiver operacional.",
      "faqPitanje3": "Como posso contactar a estação?",
      "faqOdgovor3": "Os contatos serão publicados após a conclusão da construção.",
      "faqPitanje4": "Haverá descontos para estudantes e aposentados?",
      "faqOdgovor4": "Estão previstos descontos para estudantes e aposentados.",
      "istorijaNaslovTab": "História",
      "istorijaNaslov": "História da estação de Pljevlja",
      "istorijaTekst1": "A estação de Pljevlja está planejada como um importante nó de transporte na região.",
      "istorijaTekst2": "A estação deve melhorar a conectividade da cidade com o resto do país e da região.",
      "istorijaTekst3": "Detalhes sobre construção, capacidade e abertura serão publicados após a finalização do projeto.",
      "Pravila_Privatnosti": "Política de privacidade",
      "privatnostNaslov": "Exemplo de política de privacidade",
      "privatnostPodnaslov": "Política de privacidade",
      "privatnostPrikupljanje": "Coleta de informações",
      "privatnostKorisćenje": "Uso das informações",
      "privatnostDijeljenje": "Compartilhamento de informações",
      "privatnostSigurnost": "Segurança das informações",
      "privatnostVasaPrava": "Seus direitos",
      "privatnostPromjene": "Alterações na política",
      "privatnostKontakt": "Contate-nos",
      "privatnostP1": "Esta política de privacidade descreve como coletamos, usamos e compartilhamos informações sobre você ao usar nosso site.",
      "privatnostP2": "Coletamos informações fornecidas voluntariamente ao se registrar, assinar a newsletter ou entrar em contato pelo formulário.",
      "privatnostP3": "Usamos suas informações apenas para o propósito para o qual foram fornecidas.",
      "privatnostP4": "Não compartilhamos seus dados pessoais com terceiros, exceto quando exigido por lei.",
      "privatnostP5": "Tomamos todas as medidas razoáveis para proteger seus dados.",
      "privatnostP6": "Você pode solicitar acesso, correção ou exclusão de seus dados a qualquer momento.",
      "privatnostP7": "Reservamo-nos o direito de atualizar esta política periodicamente.",
      "privatnostP8": "Se tiver dúvidas, entre em contato por e-mail ou pelo formulário no site.",
      "thDetalji": "Detalhes",
      "porukaPretrage": "Selecione os parâmetros e clique em Pesquisar para ver o horário.",
      "closeDetaljiModal": "Ainda não!",
      "trajanje_voznje": "Duração da viagem",
      "kolosjek": "Trilho",
      "slobodna_mjesta": "Lugares livres",
      "katStanica": "Estação",
      "katVozovi": "Trens",
      "katIstorija": "História",
      "katOkolina": "Arredores",
      "mapaRuta": "Rota no mapa",
      "stanica_Пљевља": "Pljevlja",
"stanica_Подгорица": "Podgorica",
"stanica_Бар": "Bar",
      "lokacija": "Localização",
    }
  },
  "ar": {
    translation: {
      "title": "محطة قطار بلييفليا",
      "naslov": "محطة القطار \"بلييفليا\" غير موجودة، هذا تمرين برمجي!",
      "podnaslov": "مرحبًا بكم في الصفحة الرسمية!",
      "footer": "&copy; 20__ محطة قطار بلييفليا",
      "navNaslovna": "الرئيسية",
      "navKontakt": "اتصال",
      "navVozniRed": "جدول المواعيد",
      "navGalerija": "معرض الصور",
      "navInformacije": "معلومات",
      "navOpsteInformacije": "معلومات عامة",
      "navFAQ": "الأسئلة الشائعة",
      "navIstorija": "التاريخ",
      "p1": "مرحبًا بكم في الصفحة الرسمية لمحطة قطار بلييفليا!",
      "p2": "هنا تجد جميع المعلومات حول الجداول، الاتصالات ومعرض الصور.",
      "p3": "للمزيد من المعلومات، اختر خيارًا من القائمة.",
      "p4": "شكرًا لزيارتكم موقعنا!",
      "p5": "إذا كان لديك أي استفسار أو اقتراح، يرجى التواصل معنا.",
      "p6": "مع أطيب التحيات،",
      "p7": "محطة قطار بلييفليا",
      "kontaktNaslov": "اتصال",
      "kontaktInfo": "معلومات الاتصال",
      "adresa": "العنوان: محطة قطار بلييفليا، بلييفليا، الجبل الأسود",
      "telefon": "الهاتف: +382 555666555",
      "email": "البريد الإلكتروني: info@zeljeznickastanicapljevlja.me",
      "posaljitePoruku": "إرسال رسالة",
      "lblIme": "الاسم:",
      "lblPrezime": "الكنية:",
      "lblEmail": "البريد الإلكتروني:",
      "lblPoruka": "الرسالة:",
      "btnPosalji": "إرسال",
      "ime": "الاسم",
      "prezime": "الكنية",
      "poruka": "الرسالة",
      "adresaLabel": "العنوان:",
      "telefonLabel": "الهاتف:",
      "emailLabel": "البريد الإلكتروني:",
      "radnoVremeLabel": "ساعات العمل:",
      "radnoVremeVrednost": "07:00 – 20:00 (الاثنين–الأحد)",
      "galerijaNaslov": "معرض محطات القطار",
      "opis1": "محطة بودغوريتسا (2013)",
      "opis2": "محطة بار (2013)",
      "opis3": "محطة بار (2019)",
      "opis4": "محطة بودغوريتسا (2019)",
      "opis5": "منصات محطة بار",
      "alt1": "محطة بودغوريتسا",
      "alt2": "محطة بار",
      "alt3": "محطة بار 2019",
      "alt4": "محطة بودغوريتسا 2019",
      "alt5": "منصات محطة بار",
      "informacijeNaslov": "معلومات",
      "nemaVozova": "لا توجد قطارات حالياً.",
      "pretrazi": "بحث",
      "datum": "التاريخ",
      "polazak": "المغادرة",
      "dolazak": "الوصول",
      "od": "من",
      "ka": "إلى",
      "prevoznik": "شركة النقل",
      "tipKarte": "نوع التذكرة",
      "rezervacija": "حجز",
      "placanje": "الدفع",
      "student": "خصم الطلاب",
      "penzioner": "خصم المتقاعدين",
      "cena": "السعر",
      "napomena": "ملاحظة",
      "lblOd": "من:",
      "lblKa": "إلى:",
      "lblDatum": "التاريخ:",
      "btnPretrazi": "بحث",
      "thDatum": "التاريخ",
      "thPolazak": "المغادرة",
      "thDolazak": "الوصول",
      "thOd": "من",
      "thKa": "إلى",
      "thPrevoznik": "شركة النقل",
      "thTipKarte": "نوع التذكرة",
      "thRezervacija": "حجز",
      "thPlacanje": "الدفع",
      "thStudent": "خصم الطلاب",
      "thPenzioner": "خصم المتقاعدين",
      "thCena": "السعر",
      "thNapomena": "ملاحظة",
      "thSlobodnaMjesta": "أماكن شاغرة",
      "thRezervisanoMjesta": "أماكن محجوزة",
      "thUkupnoMjesta": "إجمالي الأماكن",
      "thCijenaKarte": "سعر التذكرة",
      "thTipVoznje": "نوع الرحلة",
      "thVoz": "قطار",
      "thVozniRed": "جدول المواعيد",
      "thVozniRedDatum": "التاريخ",
      "thVozniRedVrijeme": "الوقت",
      "thVozniRedPolazak": "المغادرة",
      "thVozniRedDolazak": "الوصول",
      "thVozniRedOd": "من",
      "thVozniRedKa": "إلى",
      "thVozniRedPrevoznik": "شركة النقل",
      "thVozniRedTipKarte": "نوع التذكرة",
      "thVozniRedRezervacija": "حجز",
      "thVozniRedPlacanje": "الدفع",
      "thVozniRedStudent": "خصم الطلاب",
      "thVozniRedPenzioner": "خصم المتقاعدين",
      "thVozniRedCena": "السعر",
      "thVozniRedNapomena": "ملاحظة",
      "placanje_online": "دفع عبر الإنترنت",
      "placanje_gotovina": "دفع نقداً",
      "placanje_kartica": "دفع بالبطاقة",
      "placanje_PayPal": "دفع عبر PayPal",
      "placanjeStripe": "سترايب",
      "placanjeOnline": "دفع عبر الإنترنت",
      "Pređи_na_plaćanje": "انتقل إلى الدفع",
      "Kupi_kartu": "شراء التذكرة",
      "Ipak_ne": "ليس بعد.",
      "uplatnaForma": "نموذج الدفع",
      "sql_modal": "اختر طريقة الدفع:",
      "Izaberite_način_plaćanja": "اختر طريقة الدفع:",
      "kupovinaNijeDostupna": "الشراء عبر الإنترنت غير متاح لهذا الانطلاق. يرجى الاتصال بالمحطة لمزيد من المعلومات.",
      "nijeIzabranPolazak": "لم يتم اختيار الانطلاق.",
      "nema_podataka": "لا توجد بيانات",
      "closeModal": "ليس بعد!",
      "broj_telefona": "رقم الهاتف",
      "email_adresa": "البريد الإلكتروني",
      "adresa_stanice": "عنوان المحطة",
      "radno_vrijeme": "ساعات العمل",
      "radno_vrijeme_vrijednost": "07:00 – 20:00 (الاثنين–الأحد)",
      "brojSlobodnihMjesta": "عدد الأماكن الشاغرة",
      "detaljiPolaska": "تفاصيل الانطلاق",
      "naslovTab": "جدول المواعيد",
      "rezervacija_da": "نعم",
      "rezervacija_ne": "لا",
      "footerZvanicniLinkovi": "روابط رسمية",
      "footerLinkZCG": "سكك حديد الجبل الأسود",
      "footerLinkZICG": "بنية السكك الحديدية للجبل الأسود",
      "footerLinkVlada": "حكومة الجبل الأسود",
      "footerLinkOpština": "بلدية بلييفليا",
      "footerLinkTOP": "منظمة السياحة بلييفليا",
      "footerLinkJUCKPV": "المركز الثقافي بلييفليا",
      "footerDrustveneMreze": "وسائل التواصل الاجتماعي",
      "footerFacebook": "فيسبوك",
      "footerInstagram": "إنستغرام",
      "footerTwitter": "تويتر",
      "footerQRNaslov": "رمز QR",
      "footerQROpis": "امسح رمز QR للوصول السريع إلى خدماتنا ومعلوماتنا.",
      "footerQRAlt": "رمز QR لمحطة بلييفليا",
      "faqNaslovTab": "الأسئلة الشائعة",
      "faqNaslov": "الأسئلة الشائعة (FAQ)",
      "faqPitanje1": "هل يمكن شراء التذكرة عبر الإنترنت؟",
      "faqOdgovor1": "حالياً لا يمكن شراء التذكرة عبر الإنترنت لأن المحطة لم تُبنى بعد.",
      "faqPitanje2": "أين يمكنني الحصول على مزيد من المعلومات حول الانطلاقات؟",
      "faqOdgovor2": "جميع المعلومات ستكون متاحة على هذا الموقع عند تشغيل المحطة.",
      "faqPitanje3": "كيف يمكنني التواصل مع المحطة؟",
      "faqOdgovor3": "سيتم نشر بيانات الاتصال بعد الانتهاء من البناء.",
      "faqPitanje4": "هل ستكون هناك خصومات للطلاب والمتقاعدين؟",
      "faqOdgovor4": "سيتم توفير خصومات للطلاب والمتقاعدين.",
      "istorijaNaslovTab": "التاريخ",
      "istorijaNaslov": "تاريخ محطة بلييفليا",
      "istorijaTekst1": "تُخطط محطة بلييفليا لتكون مركز نقل هام في المنطقة.",
      "istorijaTekst2": "ستعمل المحطة على تحسين ربط المدينة بباقي البلاد والمنطقة.",
      "istorijaTekst3": "سيتم نشر تفاصيل حول البناء والسعة والافتتاح بعد الانتهاء من المشروع.",
      "Pravila_Privatnosti": "سياسة الخصوصية",
      "privatnostNaslov": "مثال على سياسة الخصوصية",
      "privatnostPodnaslov": "سياسة الخصوصية",
      "privatnostPrikupljanje": "جمع المعلومات",
      "privatnostKorisćenje": "استخدام المعلومات",
      "privatnostDijeljenje": "مشاركة المعلومات",
      "privatnostSigurnost": "أمان المعلومات",
      "privatnostVasaPrava": "حقوقك",
      "privatnostPromjene": "تغييرات السياسة",
      "privatnostKontakt": "اتصل بنا",
      "privatnostP1": "توضح سياسة الخصوصية هذه كيفية جمعنا واستخدامنا ومشاركة معلوماتك عند استخدام موقعنا.",
      "privatnostP2": "نجمع المعلومات التي تقدمها طوعًا عند التسجيل أو الاشتراك في النشرة الإخبارية أو التواصل عبر النموذج.",
      "privatnostP3": "نستخدم معلوماتك فقط للغرض الذي قدمت من أجله.",
      "privatnostP4": "لا نشارك بياناتك الشخصية مع أطراف ثالثة إلا إذا كان ذلك مطلوبًا بموجب القانون.",
      "privatnostP5": "نتخذ جميع التدابير المعقولة لحماية بياناتك.",
      "privatnostP6": "يمكنك طلب الوصول إلى بياناتك أو تصحيحها أو حذفها في أي وقت.",
      "privatnostP7": "نحتفظ بالحق في تحديث هذه السياسة بشكل دوري.",
      "privatnostP8": "إذا كان لديك أي استفسار، يرجى التواصل عبر البريد الإلكتروني أو النموذج على الموقع.",
      "thDetalji": "تفاصيل",
      "porukaPretrage": "حدد المعايير واضغط بحث لعرض الجدول.",
      "closeDetaljiModal": "ليس بعد!",
      "trajanje_voznje": "مدة الرحلة",
      "kolosjek": "مسار",
      "slobodna_mjesta": "أماكن شاغرة",
      "katStanica": "محطة",
      "katVozovi": "قطارات",
      "katIstorija": "تاريخ",
      "katOkolina": "المنطقة المحيطة",
      "mapaRuta": "المسار على الخريطة",
      "stanica_Пљевља": "بلييفليا",
"stanica_Подгорица": "بودغوريتسا",
"stanica_Бар": "بار",
      "lokacija": "الموقع",
    }
  },
  "fa": {
    translation: {
      "title": "ایستگاه راه‌آهن پلیولیا",
      "naslov": "ایستگاه راه‌آهن \"پلیولیا\" وجود ندارد، این یک تمرین برنامه‌نویسی است!",
      "podnaslov": "به صفحه رسمی خوش آمدید!",
      "footer": "&copy; 20__ ایستگاه راه‌آهن پلیولیا",
      "navNaslovna": "خانه",
      "navKontakt": "تماس",
      "navVozniRed": "برنامه حرکت",
      "navGalerija": "گالری",
      "navInformacije": "اطلاعات",
      "navOpsteInformacije": "اطلاعات کلی",
      "navFAQ": "سؤالات متداول",
      "navIstorija": "تاریخچه",
      "p1": "به صفحه رسمی ایستگاه راه‌آهن پلیولیا خوش آمدید!",
      "p2": "در اینجا تمام اطلاعات مربوط به برنامه حرکت، تماس‌ها و گالری تصاویر را خواهید یافت.",
      "p3": "برای اطلاعات بیشتر، یک گزینه از منو انتخاب کنید.",
      "p4": "از بازدید شما از سایت ما سپاسگزاریم!",
      "p5": "در صورت داشتن سؤال یا پیشنهاد، با ما تماس بگیرید.",
      "p6": "با احترام،",
      "p7": "ایستگاه راه‌آهن پلیولیا",
      "kontaktNaslov": "تماس",
      "kontaktInfo": "اطلاعات تماس",
      "adresa": "آدرس: ایستگاه راه‌آهن پلیولیا، پلیولیا، مونته‌نگرو",
      "telefon": "تلفن: +382 555666555",
      "email": "ایمیل: info@zeljeznickastanicapljevlja.me",
      "posaljitePoruku": "ارسال پیام",
      "lblIme": "نام:",
      "lblPrezime": "نام خانوادگی:",
      "lblEmail": "ایمیل:",
      "lblPoruka": "پیام:",
      "btnPosalji": "ارسال",
      "ime": "نام",
      "prezime": "نام خانوادگی",
      "poruka": "پیام",
      "adresaLabel": "آدرس:",
      "telefonLabel": "تلفن:",
      "emailLabel": "ایمیل:",
      "radnoVremeLabel": "ساعات کاری:",
      "radnoVremeVrednost": "07:00 – 20:00 (دوشنبه–یکشنبه)",
      "galerijaNaslov": "گالری ایستگاه‌های راه‌آهن",
      "opis1": "ایستگاه پودگوریتسا (۲۰۱۳)",
      "opis2": "ایستگاه بار (۲۰۱۳)",
      "opis3": "ایستگاه بار (۲۰۱۹)",
      "opis4": "ایستگاه پودگوریتسا (۲۰۱۹)",
      "opis5": "سکوهای ایستگاه بار",
      "alt1": "ایستگاه پودگوریتسا",
      "alt2": "ایستگاه بار",
      "alt3": "ایستگاه بار ۲۰۱۹",
      "alt4": "ایستگاه پودگوریتسا ۲۰۱۹",
      "alt5": "سکوهای ایستگاه بار",
      "informacijeNaslov": "اطلاعات",
      "nemaVozova": "در حال حاضر قطاری وجود ندارد.",
      "pretrazi": "جستجو",
      "datum": "تاریخ",
      "polazak": "حرکت",
      "dolazak": "ورود",
      "od": "از",
      "ka": "به",
      "prevoznik": "شرکت حمل‌ونقل",
      "tipKarte": "نوع بلیت",
      "rezervacija": "رزرو",
      "placanje": "پرداخت",
      "student": "تخفیف دانشجویی",
      "penzioner": "تخفیف بازنشستگان",
      "cena": "قیمت",
      "napomena": "توضیح",
      "lblOd": "از:",
      "lblKa": "به:",
      "lblDatum": "تاریخ:",
      "btnPretrazi": "جستجو",
      "thDatum": "تاریخ",
      "thPolazak": "حرکت",
      "thDolazak": "ورود",
      "thOd": "از",
      "thKa": "به",
      "thPrevoznik": "شرکت حمل‌ونقل",
      "thTipKarte": "نوع بلیت",
      "thRezervacija": "رزرو",
      "thPlacanje": "پرداخت",
      "thStudent": "تخفیف دانشجویی",
      "thPenzioner": "تخفیف بازنشستگان",
      "thCena": "قیمت",
      "thNapomena": "توضیح",
      "thSlobodnaMjesta": "صندلی‌های خالی",
      "thRezervisanoMjesta": "صندلی‌های رزرو شده",
      "thUkupnoMjesta": "کل صندلی‌ها",
      "thCijenaKarte": "قیمت بلیت",
      "thTipVoznje": "نوع سفر",
      "thVoz": "قطار",
      "thVozniRed": "برنامه حرکت",
      "thVozniRedDatum": "تاریخ",
      "thVozniRedVrijeme": "زمان",
      "thVozniRedPolazak": "حرکت",
      "thVozniRedDolazak": "ورود",
      "thVozniRedOd": "از",
      "thVozniRedKa": "به",
      "thVozniRedPrevoznik": "شرکت حمل‌ونقل",
      "thVozniRedTipKarte": "نوع بلیت",
      "thVozniRedRezervacija": "رزرو",
      "thVozniRedPlacanje": "پرداخت",
      "thVozniRedStudent": "تخفیف دانشجویی",
      "thVozniRedPenzioner": "تخفیف بازنشستگان",
      "thVozniRedCena": "قیمت",
      "thVozniRedNapomena": "توضیح",
      "placanje_online": "پرداخت آنلاین",
      "placanje_gotovina": "پرداخت نقدی",
      "placanje_kartica": "پرداخت با کارت",
      "placanje_PayPal": "پرداخت با PayPal",
      "placanjeStripe": "استرایپ",
      "placanjeOnline": "پرداخت آنلاین",
      "Pređи_na_plaćanje": "رفتن به پرداخت",
      "Kupi_kartu": "خرید بلیت",
      "Ipak_ne": "هنوز نه.",
      "uplatnaForma": "فرم پرداخت",
      "sql_modal": "روش پرداخت را انتخاب کنید:",
      "Izaberite_način_plaćanja": "روش پرداخت را انتخاب کنید:",
      "kupovinaNijeDostupna": "خرید آنلاین برای این حرکت در دسترس نیست. برای اطلاعات بیشتر با ایستگاه تماس بگیرید.",
      "nijeIzabranPolazak": "حرکت انتخاب نشده است.",
      "nema_podataka": "داده‌ای وجود ندارد",
      "closeModal": "هنوز نه!",
      "broj_telefona": "شماره تلفن",
      "email_adresa": "آدرس ایمیل",
      "adresa_stanice": "آدرس ایستگاه",
      "radno_vrijeme": "ساعات کاری",
      "radno_vrijeme_vrijednost": "07:00 – 20:00 (دوشنبه–یکشنبه)",
      "brojSlobodnihMjesta": "تعداد صندلی‌های خالی",
      "detaljiPolaska": "جزئیات حرکت",
      "naslovTab": "برنامه حرکت",
      "rezervacija_da": "بله",
      "rezervacija_ne": "خیر",
      "footerZvanicniLinkovi": "لینک‌های رسمی",
      "footerLinkZCG": "راه‌آهن مونته‌نگرو",
      "footerLinkZICG": "زیرساخت راه‌آهن مونته‌نگرو",
      "footerLinkVlada": "دولت مونته‌نگرو",
      "footerLinkOpština": "شهرداری پلیولیا",
      "footerLinkTOP": "سازمان گردشگری پلیولیا",
      "footerLinkJUCKPV": "مرکز فرهنگی پلیولیا",
      "footerDrustveneMreze": "شبکه‌های اجتماعی",
      "footerFacebook": "فیسبوک",
      "footerInstagram": "اینستاگرام",
      "footerTwitter": "توییتر",
      "footerQRNaslov": "کد QR",
      "footerQROpis": "برای دسترسی سریع به خدمات و اطلاعات ما کد QR را اسکن کنید.",
      "footerQRAlt": "کد QR ایستگاه پلیولیا",
      "faqNaslovTab": "سؤالات متداول",
      "faqNaslov": "سؤالات متداول (FAQ)",
      "faqPitanje1": "آیا امکان خرید بلیت آنلاین وجود دارد؟",
      "faqOdgovor1": "در حال حاضر امکان خرید بلیت آنلاین وجود ندارد زیرا ایستگاه هنوز ساخته نشده است.",
      "faqPitanje2": "چگونه می‌توانم اطلاعات بیشتری درباره حرکت‌ها دریافت کنم؟",
      "faqOdgovor2": "تمام اطلاعات پس از راه‌اندازی ایستگاه در این سایت قرار خواهد گرفت.",
      "faqPitanje3": "چگونه می‌توانم با ایستگاه تماس بگیرم؟",
      "faqOdgovor3": "اطلاعات تماس پس از اتمام ساخت منتشر خواهد شد.",
      "faqPitanje4": "آیا تخفیف برای دانشجویان و بازنشستگان وجود دارد؟",
      "faqOdgovor4": "تخفیف برای دانشجویان و بازنشستگان در نظر گرفته شده است.",
      "istorijaNaslovTab": "تاریخچه",
      "istorijaNaslov": "تاریخچه ایستگاه پلیولیا",
      "istorijaTekst1": "ایستگاه پلیولیا به عنوان یک مرکز حمل‌ونقل مهم در منطقه برنامه‌ریزی شده است.",
      "istorijaTekst2": "این ایستگاه باعث بهبود ارتباط شهر با سایر نقاط کشور و منطقه خواهد شد.",
      "istorijaTekst3": "جزئیات مربوط به ساخت، ظرفیت و افتتاح پس از اتمام پروژه منتشر خواهد شد.",
      "Pravila_Privatnosti": "سیاست حفظ حریم خصوصی",
      "privatnostNaslov": "نمونه سیاست حفظ حریم خصوصی",
      "privatnostPodnaslov": "سیاست حفظ حریم خصوصی",
      "privatnostPrikupljanje": "جمع‌آوری اطلاعات",
      "privatnostKorisćenje": "استفاده از اطلاعات",
      "privatnostDijeljenje": "اشتراک‌گذاری اطلاعات",
      "privatnostSigurnost": "امنیت اطلاعات",
      "privatnostVasaPrava": "حقوق شما",
      "privatnostPromjene": "تغییرات سیاست",
      "privatnostKontakt": "تماس با ما",
      "privatnostP1": "این سیاست حفظ حریم خصوصی توضیح می‌دهد که چگونه اطلاعات شما را هنگام استفاده از سایت جمع‌آوری، استفاده و به اشتراک می‌گذاریم.",
      "privatnostP2": "اطلاعاتی که به صورت داوطلبانه هنگام ثبت‌نام، عضویت در خبرنامه یا تماس از طریق فرم ارائه می‌دهید جمع‌آوری می‌شود.",
      "privatnostP3": "ما فقط برای هدفی که اطلاعات ارائه شده استفاده می‌کنیم.",
      "privatnostP4": "اطلاعات شخصی شما را با اشخاص ثالث به اشتراک نمی‌گذاریم مگر در صورت الزام قانونی.",
      "privatnostP5": "تمام اقدامات لازم برای محافظت از داده‌های شما را انجام می‌دهیم.",
      "privatnostP6": "شما می‌توانید در هر زمان درخواست دسترسی، اصلاح یا حذف داده‌های خود را داشته باشید.",
      "privatnostP7": "حق به‌روزرسانی این سیاست را به صورت دوره‌ای برای خود محفوظ می‌دانیم.",
      "privatnostP8": "در صورت داشتن سؤال، از طریق ایمیل یا فرم سایت با ما تماس بگیرید.",
      "thDetalji": "جزئیات",
      "porukaPretrage": "پارامترها را انتخاب کرده و برای مشاهده برنامه حرکت روی جستجو کلیک کنید.",
      "closeDetaljiModal": "هنوز نه!",
      "trajanje_voznje": "مدت سفر",
      "kolosjek": "ریل",
      "slobodna_mjesta": "صندلی‌های خالی",
      "katStanica": "ایستگاه",
      "katVozovi": "قطارها",
      "katIstorija": "تاریخچه",
      "katOkolina": "اطراف",
      "mapaRuta": "مسیر روی نقشه",
      "stanica_Пљевља": "پلیولیا",
"stanica_Подгорица": "پودگوریتسا",
"stanica_Бар": "بار",
      "lokacija": "مکان",
    }
  }, 
  "mi": {
  translation: {
    "title": "Teihana Rerewē o Pljevlja",
    "naslov": "KĀORE TE TEIHANA REREWĒ \"PLJEVLJA\" I TĒNEI, HE MAHI PŪMANAWA TĒNEI!",
    "podnaslov": "Nau mai ki te whārangi whaimana!",
    "footer": "&copy; 20__ Teihana Rerewē o Pljevlja",
    "navNaslovna": "Kāinga",
    "navKontakt": "Whakapā",
    "navVozniRed": "Rārangi Waka",
    "navGalerija": "Whakaahua",
    "navInformacije": "Ngā mōhiohio",
    "navOpsteInformacije": "Ngā mōhiohio whānui",
    "navFAQ": "Ngā pātai auau",
    "navIstorija": "Hītori",
    "p1": "Nau mai ki te whārangi whaimana o Teihana Rerewē o Pljevlja!",
    "p2": "Kei konei ngā mōhiohio katoa mō ngā rārangi waka, whakapā me te whakaahua.",
    "p3": "Mō ētahi atu mōhiohio, tīpakohia tētahi kōwhiringa i te tahua.",
    "p4": "Ngā mihi mō tō toro mai ki tā mātou pae tukutuku!",
    "p5": "Mēnā he pātai, he whakaaro rānei, whakapā mai.",
    "p6": "Ngā mihi nui,",
    "p7": "Teihana Rerewē o Pljevlja",
    "kontaktNaslov": "Whakapā",
    "kontaktInfo": "Ngā mōhiohio whakapā",
    "adresa": "Wāhi noho: Teihana Rerewē o Pljevlja, Pljevlja, Montenegro",
    "telefon": "Waea: +382 555666555",
    "email": "Īmēra: info@zeljeznickastanicapljevlja.me",
    "posaljitePoruku": "Tukua he karere",
    "lblIme": "Ingoa:",
    "lblPrezime": "Ingoa whānau:",
    "lblEmail": "Īmēra:",
    "lblPoruka": "Karere:",
    "btnPosalji": "Tukua",
    "ime": "Ingoa",
    "prezime": "Ingoa whānau",
    "poruka": "Karere",
    "adresaLabel": "Wāhi noho:",
    "telefonLabel": "Waea:",
    "emailLabel": "Īmēra:",
    "radnoVremeLabel": "Ngā haora mahi:",
    "radnoVremeVrednost": "07:00 – 20:00 (Rāhina–Rātapu)",
    "galerijaNaslov": "Whakaahua o ngā teihana rerewē",
    "opis1": "Teihana Podgorica (2013)",
    "opis2": "Teihana Bar (2013)",
    "opis3": "Teihana Bar (2019)",
    "opis4": "Teihana Podgorica (2019)",
    "opis5": "Ngā papa o Teihana Bar",
    "alt1": "Teihana Podgorica",
    "alt2": "Teihana Bar",
    "alt3": "Teihana Bar 2019",
    "alt4": "Teihana Podgorica 2019",
    "alt5": "Ngā papa o Teihana Bar",
    "informacijeNaslov": "Ngā mōhiohio",
    "nemaVozova": "Kāore he tereina i tēnei wā.",
    "pretrazi": "Rapua",
    "datum": "Rā",
    "polazak": "Haere",
    "dolazak": "Taenga",
    "od": "Mai",
    "ka": "Ki",
    "prevoznik": "Kaiwhakarato",
    "tipKarte": "Momo tīkiti",
    "rezervacija": "Rahuitanga",
    "placanje": "Utu",
    "student": "Utu ākonga",
    "penzioner": "Utu kaumātua",
    "cena": "Utu",
    "napomena": "Tuhipoka",
    "lblOd": "Mai:",
    "lblKa": "Ki:",
    "lblDatum": "Rā:",
    "btnPretrazi": "Rapua",
    "thDatum": "Rā",
    "thPolazak": "Haere",
    "thDolazak": "Taenga",
    "thOd": "Mai",
    "thKa": "Ki",
    "thPrevoznik": "Kaiwhakarato",
    "thTipKarte": "Momo tīkiti",
    "thRezervacija": "Rahuitanga",
    "thPlacanje": "Utu",
    "thStudent": "Utu ākonga",
    "thPenzioner": "Utu kaumātua",
    "thCena": "Utu",
    "thNapomena": "Tuhipoka",
    "thSlobodnaMjesta": "Ngā nohoanga wātea",
    "thRezervisanoMjesta": "Ngā nohoanga kua rahuitia",
    "thUkupnoMjesta": "Tapeke nohoanga",
    "thCijenaKarte": "Utu tīkiti",
    "thTipVoznje": "Momo haerenga",
    "thVoz": "Tereina",
    "thVozniRed": "Rārangi Waka",
    "thVozniRedDatum": "Rā",
    "thVozniRedVrijeme": "Wā",
    "thVozniRedPolazak": "Haere",
    "thVozniRedDolazak": "Taenga",
    "thVozniRedOd": "Mai",
    "thVozniRedKa": "Ki",
    "thVozniRedPrevoznik": "Kaiwhakarato",
    "thVozniRedTipKarte": "Momo tīkiti",
    "thVozniRedRezervacija": "Rahuitanga",
    "thVozniRedPlacanje": "Utu",
    "thVozniRedStudent": "Utu ākonga",
    "thVozniRedPenzioner": "Utu kaumātua",
    "thVozniRedCena": "Utu",
    "thVozniRedNapomena": "Tuhipoka",
    "placanje_online": "Utu tuihono",
    "placanje_gotovina": "Utu moni",
    "placanje_kartica": "Utu kāri",
    "placanje_PayPal": "Utu mā PayPal",
    "placanjeStripe": "Stripe",
    "placanjeOnline": "Utu tuihono",
    "Pređи_na_plaćanje": "Haere ki te utu",
    "Kupi_kartu": "Hokona tīkiti",
    "Ipak_ne": "Kāore anō.",
    "uplatnaForma": "Puka utu",
    "sql_modal": "Kōwhiria te tikanga utu:",
    "Izaberite_način_plaćanja": "Kōwhiria te tikanga utu:",
    "kupovinaNijeDostupna": "Kāore e wātea ana te hoko tuihono mō tēnei haerenga. Whakapā atu ki te teihana mō ētahi atu mōhiohio.",
    "nijeIzabranPolazak": "Kāore i tīpakohia te haerenga.",
    "nema_podataka": "Kāore he raraunga",
    "closeModal": "Kāore anō!",
    "broj_telefona": "Tau waea",
    "email_adresa": "Wāhitau īmēra",
    "adresa_stanice": "Wāhi noho teihana",
    "radno_vrijeme": "Ngā haora mahi",
    "radno_vrijeme_vrijednost": "07:00 – 20:00 (Rāhina–Rātapu)",
    "brojSlobodnihMjesta": "Tau nohoanga wātea",
    "detaljiPolaska": "Ngā taipitopito haerenga",
    "naslovTab": "Rārangi Waka",
    "rezervacija_da": "Āe",
    "rezervacija_ne": "Kāo",
    "footerZvanicniLinkovi": "Ngā hononga whaimana",
    "footerLinkZCG": "Ngā Rerewē o Montenegro",
    "footerLinkZICG": "Hanganga Rerewē o Montenegro",
    "footerLinkVlada": "Kāwanatanga o Montenegro",
    "footerLinkOpština": "Kaunihera o Pljevlja",
    "footerLinkTOP": "Rōpū Tāpoi o Pljevlja",
    "footerLinkJUCKPV": "Pokapū Ahurea o Pljevlja",
    "footerDrustveneMreze": "Ngā pāpāho pāpori",
    "footerFacebook": "Pukamata",
    "footerInstagram": "Instagram",
    "footerTwitter": "Twitter",
    "footerQRNaslov": "Waehere QR",
    "footerQROpis": "Karapaia te waehere QR mō te uru tere ki ā mātou ratonga me ngā mōhiohio.",
    "footerQRAlt": "Waehere QR mō Teihana Pljevlja",
    "faqNaslovTab": "Ngā pātai auau",
    "faqNaslov": "Ngā pātai auau (FAQ)",
    "faqPitanje1": "Ka taea te hoko tīkiti tuihono?",
    "faqOdgovor1": "I tēnei wā kāore e taea te hoko tīkiti tuihono nā te mea kāore anō kia hangaia te teihana.",
    "faqPitanje2": "Kei hea au e whiwhi ai i ngā mōhiohio mō ngā haerenga?",
    "faqOdgovor2": "Ka wātea ngā mōhiohio katoa ki tēnei pae tukutuku ina tīmata te teihana.",
    "faqPitanje3": "Me pēhea taku whakapā atu ki te teihana?",
    "faqOdgovor3": "Ka whakaputaina ngā mōhiohio whakapā i muri i te oti o te hanganga.",
    "faqPitanje4": "He hekenga utu mō ngā ākonga me ngā kaumātua?",
    "faqOdgovor4": "Ka wātea ngā hekenga utu mō ngā ākonga me ngā kaumātua.",
    "istorijaNaslovTab": "Hītori",
    "istorijaNaslov": "Hītori o te Teihana Pljevlja",
    "istorijaTekst1": "E whakamaheretia ana te Teihana Pljevlja hei pokapū kawe waka nui mō te rohe.",
    "istorijaTekst2": "Ka whakapai ake te teihana i te hononga o te tāone ki te toenga o te whenua me te rohe.",
    "istorijaTekst3": "Ka whakaputaina ngā taipitopito mō te hanganga, te kaha me te whakatuwheratanga i muri i te oti o te kaupapa.",
    "Pravila_Privatnosti": "Kaupapa here tūmataiti",
    "privatnostNaslov": "Tauira kaupapa here tūmataiti",
    "privatnostPodnaslov": "Kaupapa here tūmataiti",
    "privatnostPrikupljanje": "Te kohikohi mōhiohio",
    "privatnostKorisćenje": "Te whakamahi mōhiohio",
    "privatnostDijeljenje": "Te tiritiri mōhiohio",
    "privatnostSigurnost": "Te haumaru mōhiohio",
    "privatnostVasaPrava": "Ō motika",
    "privatnostPromjene": "Ngā panonitanga kaupapa here",
    "privatnostKontakt": "Whakapā mai",
    "privatnostP1": "E whakamārama ana tēnei kaupapa here tūmataiti me pēhea mātou e kohikohi, whakamahi, me te tiritiri mōhiohio mōu i a koe e whakamahi ana i tā mātou pae tukutuku.",
    "privatnostP2": "Ka kohikohia ngā mōhiohio ka tukuna e koe i te wā e rēhita ana, e ohauru ana rānei, e whakapā ana rānei mā te puka.",
    "privatnostP3": "Ka whakamahia anake ō mōhiohio mō te kaupapa i tukuna ai.",
    "privatnostP4": "Kāore mātou e tiritiri i ō raraunga ki ētahi atu, engari mēnā e hiahiatia ana e te ture.",
    "privatnostP5": "Ka mahia ngā mahi tika katoa hei tiaki i ō raraunga.",
    "privatnostP6": "Ka taea e koe te tono kia uru, kia whakatika, kia muku rānei i ō raraunga i ngā wā katoa.",
    "privatnostP7": "Kei a mātou te motika ki te whakahou i tēnei kaupapa here i ia wā.",
    "privatnostP8": "Mēnā he pātai āu, whakapā mai mā te īmēra, mā te puka rānei kei te pae tukutuku.",
    "thDetalji": "Taipitopito",
    "porukaPretrage": "Tīpakohia ngā tawhā, pāwhiritia Rapua kia kite i te rārangi waka.",
    "closeDetaljiModal": "Kāore anō!",
    "trajanje_voznje": "Roanga haerenga",
    "kolosjek": "Ara rerewē",
    "slobodna_mjesta": "Ngā nohoanga wātea",
    "katStanica": "Teihana",
    "katVozovi": "Ngā tereina",
    "katIstorija": "Hītori",
    "katOkolina": "Takiwā",
    "mapaRuta": "Ara ki te mahere",
    "stanica_Пљевља": "Pljevlja",
"stanica_Подгорица": "Podgorica",
"stanica_Бар": "Bar",
    "lokacija": "Wāhi",
  }
    },
    "sw": {
  translation: {
    "title": "Stesheni ya Reli ya Pljevlja",
    "naslov": "STESHENI YA RELI \"PLJEVLJA\" HAIIPO, HII NI ZOEZI LA PROGRAMU!",
    "podnaslov": "Karibu kwenye ukurasa rasmi!",
    "footer": "&copy; 20__ Stesheni ya Reli ya Pljevlja",
    "navNaslovna": "Nyumbani",
    "navKontakt": "Mawasiliano",
    "navVozniRed": "Ratiba",
    "navGalerija": "Matukio",
    "navInformacije": "Taarifa",
    "navOpsteInformacije": "Taarifa za jumla",
    "navFAQ": "Maswali ya mara kwa mara",
    "navIstorija": "Historia",
    "p1": "Karibu kwenye ukurasa rasmi wa Stesheni ya Reli ya Pljevlja!",
    "p2": "Hapa utapata taarifa zote kuhusu ratiba, mawasiliano na matukio ya picha.",
    "p3": "Kwa taarifa zaidi, chagua chaguo kwenye menyu.",
    "p4": "Asante kwa kutembelea tovuti yetu!",
    "p5": "Ikiwa una swali au pendekezo, wasiliana nasi.",
    "p6": "Kwa heshima,",
    "p7": "Stesheni ya Reli ya Pljevlja",
    "kontaktNaslov": "Mawasiliano",
    "kontaktInfo": "Taarifa za mawasiliano",
    "adresa": "Anwani: Stesheni ya Reli ya Pljevlja, Pljevlja, Montenegro",
    "telefon": "Simu: +382 555666555",
    "email": "Barua pepe: info@zeljeznickastanicapljevlja.me",
    "posaljitePoruku": "Tuma ujumbe",
    "lblIme": "Jina:",
    "lblPrezime": "Jina la ukoo:",
    "lblEmail": "Barua pepe:",
    "lblPoruka": "Ujumbe:",
    "btnPosalji": "Tuma",
    "ime": "Jina",
    "prezime": "Jina la ukoo",
    "poruka": "Ujumbe",
    "adresaLabel": "Anwani:",
    "telefonLabel": "Simu:",
    "emailLabel": "Barua pepe:",
    "radnoVremeLabel": "Saa za kazi:",
    "radnoVremeVrednost": "07:00 – 20:00 (Jumatatu–Jumapili)",
    "galerijaNaslov": "Matukio ya stesheni za reli",
    "opis1": "Stesheni ya Podgorica (2013)",
    "opis2": "Stesheni ya Bar (2013)",
    "opis3": "Stesheni ya Bar (2019)",
    "opis4": "Stesheni ya Podgorica (2019)",
    "opis5": "Majukwaa ya Stesheni ya Bar",
    "alt1": "Stesheni ya Podgorica",
    "alt2": "Stesheni ya Bar",
    "alt3": "Stesheni ya Bar 2019",
    "alt4": "Stesheni ya Podgorica 2019",
    "alt5": "Majukwaa ya Stesheni ya Bar",
    "informacijeNaslov": "Taarifa",
    "nemaVozova": "Hakuna treni kwa sasa.",
    "pretrazi": "Tafuta",
    "datum": "Tarehe",
    "polazak": "Kuondoka",
    "dolazak": "Kufika",
    "od": "Kutoka",
    "ka": "Kwenda",
    "prevoznik": "Mtoa huduma",
    "tipKarte": "Aina ya tiketi",
    "rezervacija": "Uhifadhi",
    "placanje": "Malipo",
    "student": "Punguzo la mwanafunzi",
    "penzioner": "Punguzo la mstaafu",
    "cena": "Bei",
    "napomena": "Kumbuka",
    "lblOd": "Kutoka:",
    "lblKa": "Kwenda:",
    "lblDatum": "Tarehe:",
    "btnPretrazi": "Tafuta",
    "thDatum": "Tarehe",
    "thPolazak": "Kuondoka",
    "thDolazak": "Kufika",
    "thOd": "Kutoka",
    "thKa": "Kwenda",
    "thPrevoznik": "Mtoa huduma",
    "thTipKarte": "Aina ya tiketi",
    "thRezervacija": "Uhifadhi",
    "thPlacanje": "Malipo",
    "thStudent": "Punguzo la mwanafunzi",
    "thPenzioner": "Punguzo la mstaafu",
    "thCena": "Bei",
    "thNapomena": "Kumbuka",
    "thSlobodnaMjesta": "Viti vilivyo wazi",
    "thRezervisanoMjesta": "Viti vilivyohifadhiwa",
    "thUkupnoMjesta": "Jumla ya viti",
    "thCijenaKarte": "Bei ya tiketi",
    "thTipVoznje": "Aina ya safari",
    "thVoz": "Treni",
    "thVozniRed": "Ratiba",
    "thVozniRedDatum": "Tarehe",
    "thVozniRedVrijeme": "Muda",
    "thVozniRedPolazak": "Kuondoka",
    "thVozniRedDolazak": "Kufika",
    "thVozniRedOd": "Kutoka",
    "thVozniRedKa": "Kwenda",
    "thVozniRedPrevoznik": "Mtoa huduma",
    "thVozniRedTipKarte": "Aina ya tiketi",
    "thVozniRedRezervacija": "Uhifadhi",
    "thVozniRedPlacanje": "Malipo",
    "thVozniRedStudent": "Punguzo la mwanafunzi",
    "thVozniRedPenzioner": "Punguzo la mstaafu",
    "thVozniRedCena": "Bei",
    "thVozniRedNapomena": "Kumbuka",
    "placanje_online": "Malipo mtandaoni",
    "placanje_gotovina": "Malipo taslimu",
    "placanje_kartica": "Malipo kwa kadi",
    "placanje_PayPal": "Malipo kwa PayPal",
    "placanjeStripe": "Stripe",
    "placanjeOnline": "Malipo mtandaoni",
    "Pređи_na_plaćanje": "Nenda kwenye malipo",
    "Kupi_kartu": "Nunua tiketi",
    "Ipak_ne": "Bado hapana.",
    "uplatnaForma": "Fomu ya malipo",
    "sql_modal": "Chagua njia ya malipo:",
    "Izaberite_način_plaćanja": "Chagua njia ya malipo:",
    "kupovinaNijeDostupna": "Ununuzi mtandaoni haupatikani kwa safari hii. Tafadhali wasiliana na stesheni kwa taarifa zaidi.",
    "nijeIzabranPolazak": "Safari haijachaguliwa.",
    "nema_podataka": "Hakuna data",
    "closeModal": "Bado hapana!",
    "broj_telefona": "Nambari ya simu",
    "email_adresa": "Anwani ya barua pepe",
    "adresa_stanice": "Anwani ya stesheni",
    "radno_vrijeme": "Saa za kazi",
    "radno_vrijeme_vrijednost": "07:00 – 20:00 (Jumatatu–Jumapili)",
    "brojSlobodnihMjesta": "Idadi ya viti vilivyo wazi",
    "detaljiPolaska": "Maelezo ya safari",
    "naslovTab": "Ratiba",
    "rezervacija_da": "Ndiyo",
    "rezervacija_ne": "Hapana",
    "footerZvanicniLinkovi": "Viungo rasmi",
    "footerLinkZCG": "Reli ya Montenegro",
    "footerLinkZICG": "Miundombinu ya Reli ya Montenegro",
    "footerLinkVlada": "Serikali ya Montenegro",
    "footerLinkOpština": "Manispaa ya Pljevlja",
    "footerLinkTOP": "Shirika la Utalii la Pljevlja",
    "footerLinkJUCKPV": "Kituo cha Utamaduni cha Pljevlja",
    "footerDrustveneMreze": "Mitandao ya kijamii",
    "footerFacebook": "Facebook",
    "footerInstagram": "Instagram",
    "footerTwitter": "Twitter",
    "footerQRNaslov": "Msimbo wa QR",
    "footerQROpis": "Skena msimbo wa QR kwa huduma na taarifa zetu haraka.",
    "footerQRAlt": "Msimbo wa QR wa Stesheni ya Pljevlja",
    "faqNaslovTab": "Maswali ya mara kwa mara",
    "faqNaslov": "Maswali ya mara kwa mara (FAQ)",
    "faqPitanje1": "Je, inawezekana kununua tiketi mtandaoni?",
    "faqOdgovor1": "Kwa sasa haiwezekani kununua tiketi mtandaoni kwa sababu stesheni bado haijajengwa.",
    "faqPitanje2": "Ninaweza kupata wapi taarifa zaidi kuhusu safari?",
    "faqOdgovor2": "Taarifa zote zitapatikana kwenye tovuti hii mara stesheni itakapoanza kazi.",
    "faqPitanje3": "Ninawezaje kuwasiliana na stesheni?",
    "faqOdgovor3": "Taarifa za mawasiliano zitachapishwa baada ya ujenzi kukamilika.",
    "faqPitanje4": "Je, kutakuwa na punguzo kwa wanafunzi na wastaafu?",
    "faqOdgovor4": "Punguzo kwa wanafunzi na wastaafu litapatikana.",
    "istorijaNaslovTab": "Historia",
    "istorijaNaslov": "Historia ya Stesheni ya Pljevlja",
    "istorijaTekst1": "Stesheni ya Pljevlja inapangwa kuwa kitovu muhimu cha usafiri katika eneo hili.",
    "istorijaTekst2": "Stesheni itaboresha muunganiko wa mji na maeneo mengine ya nchi na kanda.",
    "istorijaTekst3": "Maelezo kuhusu ujenzi, uwezo na ufunguzi yatatolewa baada ya mradi kukamilika.",
    "Pravila_Privatnosti": "Sera ya faragha",
    "privatnostNaslov": "Mfano wa sera ya faragha",
    "privatnostPodnaslov": "Sera ya faragha",
    "privatnostPrikupljanje": "Ukusanyaji wa taarifa",
    "privatnostKorisćenje": "Matumizi ya taarifa",
    "privatnostDijeljenje": "Ushirikiano wa taarifa",
    "privatnostSigurnost": "Usalama wa taarifa",
    "privatnostVasaPrava": "Haki zako",
    "privatnostPromjene": "Mabadiliko ya sera",
    "privatnostKontakt": "Wasiliana nasi",
    "privatnostP1": "Sera hii ya faragha inaeleza jinsi tunavyokusanya, kutumia na kushiriki taarifa zako unapotumia tovuti yetu.",
    "privatnostP2": "Tunakusanya taarifa unazotoa kwa hiari unapojisajili, kujiunga na jarida au kuwasiliana kupitia fomu.",
    "privatnostP3": "Tunatumia taarifa zako tu kwa madhumuni uliyoitoa.",
    "privatnostP4": "Hatushirikiani taarifa zako binafsi na watu wengine isipokuwa inapohitajika kisheria.",
    "privatnostP5": "Tunachukua hatua zote zinazofaa kulinda taarifa zako.",
    "privatnostP6": "Unaweza kuomba kupata, kusahihisha au kufuta taarifa zako wakati wowote.",
    "privatnostP7": "Tuna haki ya kusasisha sera hii mara kwa mara.",
    "privatnostP8": "Ikiwa una swali, wasiliana nasi kwa barua pepe au kupitia fomu kwenye tovuti.",
    "thDetalji": "Maelezo",
    "porukaPretrage": "Chagua vigezo na bonyeza Tafuta ili kuona ratiba.",
    "closeDetaljiModal": "Bado hapana!",
    "trajanje_voznje": "Muda wa safari",
    "kolosjek": "Njia ya reli",
    "slobodna_mjesta": "Viti vilivyo wazi",
    "katStanica": "Stesheni",
    "katVozovi": "Treni",
    "katIstorija": "Historia",
    "katOkolina": "Mazingira",
    "mapaRuta": "Njia kwenye ramani",
    "stanica_Пљевља": "Pljevlja",
"stanica_Подгорица": "Podgorica",
"stanica_Бар": "Bar",
    "lokacija": "Mahali",
  }
    },
    "th": {
  translation: {
    "title": "สถานีรถไฟ Pljevlja",
    "naslov": "สถานีรถไฟ \"PLJEVLJA\" ยังไม่เปิดให้บริการ นี่เป็นการจำลองโปรแกรม!",
    "podnaslov": "ยินดีต้อนรับสู่หน้าเว็บอย่างเป็นทางการ!",
    "footer": "&copy; 20__ สถานีรถไฟ Pljevlja",
    "navNaslovna": "หน้าแรก",
    "navKontakt": "ติดต่อเรา",
    "navVozniRed": "ตารางเดินรถ",
    "navGalerija": "แกลเลอรี่",
    "navInformacije": "ข้อมูล",
    "navOpsteInformacije": "ข้อมูลทั่วไป",
    "navFAQ": "คำถามที่พบบ่อย",
    "navIstorija": "ประวัติศาสตร์",
    "p1": "ยินดีต้อนรับสู่หน้าเว็บอย่างเป็นทางการของสถานีรถไฟ Pljevlja!",
    "p2": "ที่นี่คุณจะพบข้อมูลทั้งหมดเกี่ยวกับตารางเดินรถ การติดต่อ และแกลเลอรี่ภาพถ่าย",
    "p3": "สำหรับข้อมูลเพิ่มเติม โปรดเลือกตัวเลือกจากเมนูด้านบน",
    "p4": "ขอบคุณที่เยี่ยมชมเว็บไซต์ของเรา!",
    "p5": "หากคุณมีคำถามหรือข้อเสนอแนะ โปรดติดต่อเรา",
    "p6": "ด้วยความเคารพ,",
    "p7": "สถานีรถไฟ Pljevlja",
    "kontaktNaslov": "ติดต่อเรา",
    "kontaktInfo": "ข้อมูลการติดต่อ",
    "adresa": "ที่อยู่: สถานีรถไฟ Pljevlja, Pljevlja, มอนเตเนโกร",
    "telefon": "โทรศัพท์: +382 555666555",
    "email": "อีเมล: info@zeljeznickastanicapljevlja.me",
    "posaljitePoruku": "ส่งข้อความ",
    "lblIme": "ชื่อ:",
    "lblPrezime": "นามสกุล:",
    "lblEmail": "อีเมล:",
    "lblPoruka": "ข้อความ:",
    "btnPosalji": "ส่ง",
    "ime": "ชื่อ",
    "prezime": "นามสกุล",
    "poruka": "ข้อความ",
    "adresaLabel": "ที่อยู่:",
    "telefonLabel": "โทรศัพท์:",
    "emailLabel": "อีเมล:",
    "radnoVremeLabel": "เวลาทำการ:",
    "radnoVremeVrednost": "07:00 – 20:00 (จันทร์–อาทิตย์)",
    "galerijaNaslov": "แกลเลอรี่สถานีรถไฟ",
    "opis1": "สถานี Podgorica (2013)",
    "opis2": "สถานี Bar (2013)",
    "opis3": "สถานี Bar (2019)",
    "opis4": "สถานี Podgorica (2019)",
    "opis5": "ชานชาลาสถานี Bar",
    "alt1": "สถานี Podgorica",
    "alt2": "สถานี Bar",
    "alt3": "สถานี Bar 2019",
    "alt4": "สถานี Podgorica 2019",
    "alt5": "ชานชาลาสถานี Bar",
    "informacijeNaslov": "ข้อมูล",
    "nemaVozova": "ขณะนี้ไม่มีขบวนรถไฟ",
    "pretrazi": "ค้นหา",
    "datum": "วันที่",
    "polazak": "ออกเดินทาง",
    "dolazak": "มาถึง",
    "od": "จาก",
    "ka": "ถึง",
    "prevoznik": "ผู้ให้บริการ",
    "tipKarte": "ประเภทตั๋ว",
    "rezervacija": "การจอง",
    "placanje": "การชำระเงิน",
    "student": "ส่วนลดนักเรียน",
    "penzioner": "ส่วนลดผู้เกษียณ",
    "cena": "ราคา",
    "napomena": "หมายเหตุ",
    "lblOd": "จาก:",
    "lblKa": "ถึง:",
    "lblDatum": "วันที่:",
    "btnPretrazi": "ค้นหา",
    "thDatum": "วันที่",
    "thPolazak": "ออกเดินทาง",
    "thDolazak": "มาถึง",
    "thOd": "จาก",
    "thKa": "ถึง",
    "thPrevoznik": "ผู้ให้บริการ",
    "thTipKarte": "ประเภทตั๋ว",
    "thRezervacija": "การจอง",
    "thPlacanje": "การชำระเงิน",
    "thStudent": "ส่วนลดนักเรียน",
    "thPenzioner": "ส่วนลดผู้เกษียณ",
    "thCena": "ราคา",
    "thNapomena": "หมายเหตุ",
    "thSlobodnaMjesta": "ที่นั่งว่าง",
    "thRezervisanoMjesta": "ที่นั่งจองแล้ว",
    "thUkupnoMjesta": "จำนวนที่นั่งทั้งหมด",
    "thCijenaKarte": "ราคาตั๋ว",
    "thTipVoznje": "ประเภทการเดินทาง",
    "thVoz": "รถไฟ",
    "thVozniRed": "ตารางเดินรถ",
    "thVozniRedDatum": "วันที่",
    "thVozniRedVrijeme": "เวลา",
    "thVozniRedPolazak": "ออกเดินทาง",
    "thVozniRedDolazak": "มาถึง",
    "thVozniRedOd": "จาก",
    "thVozniRedKa": "ถึง",
    "thVozniRedPrevoznik": "ผู้ให้บริการ",
    "thVozniRedTipKarte": "ประเภทตั๋ว",
    "thVozniRedRezervacija": "การจอง",
    "thVozniRedPlacanje": "การชำระเงิน",
    "thVozniRedStudent": "ส่วนลดนักเรียน",
    "thVozniRedPenzioner": "ส่วนลดผู้เกษียณ",
    "thVozniRedCena": "ราคา",
    "thVozniRedNapomena": "หมายเหตุ",
    "placanje_online": "ชำระเงินออนไลน์",
    "placanje_gotovina": "ชำระเงินสด",
    "placanje_kartica": "ชำระด้วยบัตร",
    "placanje_PayPal": "ชำระผ่าน PayPal",
    "placanjeStripe": "Stripe",
    "placanjeOnline": "ชำระเงินออนไลน์",
    "Pređи_na_plaćanje": "ไปที่การชำระเงิน",
    "Kupi_kartu": "ซื้อตั๋ว",
    "Ipak_ne": "ยังไม่ใช่",
    "uplatnaForma": "แบบฟอร์มการชำระเงิน",
    "sql_modal": "เลือกวิธีการชำระเงิน:",
    "Izaberite_način_plaćanja": "เลือกวิธีการชำระเงิน:",
    "kupovinaNijeDostupna": "ไม่สามารถซื้อออนไลน์สำหรับขบวนนี้ กรุณาติดต่อสถานีเพื่อข้อมูลเพิ่มเติม",
    "nijeIzabranPolazak": "ยังไม่ได้เลือกขบวน",
    "nema_podataka": "ไม่มีข้อมูล",
    "closeModal": "ยังไม่ใช่!",
    "broj_telefona": "หมายเลขโทรศัพท์",
    "email_adresa": "ที่อยู่อีเมล",
    "adresa_stanice": "ที่อยู่สถานี",
    "radno_vrijeme": "เวลาทำการ",
    "radno_vrijeme_vrijednost": "07:00 – 20:00 (จันทร์–อาทิตย์)",
    "brojSlobodnihMjesta": "จำนวนที่นั่งว่าง",
    "detaljiPolaska": "รายละเอียดขบวน",
    "naslovTab": "ตารางเดินรถ",
    "rezervacija_da": "ใช่",
    "rezervacija_ne": "ไม่ใช่",
    "footerZvanicniLinkovi": "ลิงก์ทางการ",
    "footerLinkZCG": "การรถไฟมอนเตเนโกร",
    "footerLinkZICG": "โครงสร้างพื้นฐานรถไฟมอนเตเนโกร",
    "footerLinkVlada": "รัฐบาลมอนเตเนโกร",
    "footerLinkOpština": "เทศบาล Pljevlja",
    "footerLinkTOP": "องค์การท่องเที่ยว Pljevlja",
    "footerLinkJUCKPV": "ศูนย์วัฒนธรรม Pljevlja",
    "footerDrustveneMreze": "โซเชียลมีเดีย",
    "footerFacebook": "Facebook",
    "footerInstagram": "Instagram",
    "footerTwitter": "Twitter",
    "footerQRNaslov": "รหัส QR",
    "footerQROpis": "สแกนรหัส QR เพื่อเข้าถึงบริการและข้อมูลของเราอย่างรวดเร็ว",
    "footerQRAlt": "รหัส QR สถานี Pljevlja",
    "faqNaslovTab": "คำถามที่พบบ่อย",
    "faqNaslov": "คำถามที่พบบ่อย (FAQ)",
    "faqPitanje1": "สามารถซื้อตั๋วออนไลน์ได้หรือไม่?",
    "faqOdgovor1": "ขณะนี้ยังไม่สามารถซื้อตั๋วออนไลน์ได้เนื่องจากสถานียังไม่เปิดให้บริการ",
    "faqPitanje2": "จะหาข้อมูลขบวนรถได้ที่ไหน?",
    "faqOdgovor2": "ข้อมูลทั้งหมดจะมีในเว็บไซต์นี้เมื่อสถานีเปิดให้บริการ",
    "faqPitanje3": "จะติดต่อสถานีได้อย่างไร?",
    "faqOdgovor3": "ข้อมูลการติดต่อจะเผยแพร่หลังจากก่อสร้างเสร็จสิ้น",
    "faqPitanje4": "จะมีส่วนลดสำหรับนักเรียนและผู้เกษียณหรือไม่?",
    "faqOdgovor4": "จะมีส่วนลดสำหรับนักเรียนและผู้เกษียณ",
    "istorijaNaslovTab": "ประวัติศาสตร์",
    "istorijaNaslov": "ประวัติสถานี Pljevlja",
    "istorijaTekst1": "สถานี Pljevlja วางแผนให้เป็นศูนย์กลางการขนส่งที่สำคัญในภูมิภาค",
    "istorijaTekst2": "สถานีจะช่วยเชื่อมโยงเมืองกับส่วนอื่น ๆ ของประเทศและภูมิภาค",
    "istorijaTekst3": "รายละเอียดเกี่ยวกับการก่อสร้าง ความจุ และการเปิดให้บริการจะเผยแพร่หลังโครงการเสร็จสิ้น",
    "Pravila_Privatnosti": "นโยบายความเป็นส่วนตัว",
    "privatnostNaslov": "ตัวอย่างนโยบายความเป็นส่วนตัว",
    "privatnostPodnaslov": "นโยบายความเป็นส่วนตัว",
    "privatnostPrikupljanje": "การเก็บข้อมูล",
    "privatnostKorisćenje": "การใช้ข้อมูล",
    "privatnostDijeljenje": "การแบ่งปันข้อมูล",
    "privatnostSigurnost": "ความปลอดภัยของข้อมูล",
    "privatnostVasaPrava": "สิทธิของคุณ",
    "privatnostPromjene": "การเปลี่ยนแปลงนโยบาย",
    "privatnostKontakt": "ติดต่อเรา",
    "privatnostP1": "นโยบายนี้อธิบายวิธีที่เรารวบรวม ใช้ และแบ่งปันข้อมูลของคุณเมื่อใช้เว็บไซต์ของเรา",
    "privatnostP2": "เรารวบรวมข้อมูลที่คุณให้โดยสมัครใจเมื่อสมัครสมาชิก จดหมายข่าว หรือกรอกแบบฟอร์มติดต่อ",
    "privatnostP3": "เราใช้ข้อมูลของคุณเพื่อวัตถุประสงค์ที่คุณให้ไว้เท่านั้น",
    "privatnostP4": "เราไม่แบ่งปันข้อมูลส่วนบุคคลของคุณกับบุคคลที่สาม เว้นแต่กฎหมายกำหนด",
    "privatnostP5": "เราดำเนินมาตรการที่เหมาะสมทั้งหมดเพื่อปกป้องข้อมูลของคุณ",
    "privatnostP6": "คุณสามารถขอเข้าถึง แก้ไข หรือขอลบข้อมูลของคุณได้ตลอดเวลา",
    "privatnostP7": "เราขอสงวนสิทธิ์ในการอัปเดตนโยบายนี้เป็นระยะ ๆ",
    "privatnostP8": "หากคุณมีคำถาม โปรดติดต่อทางอีเมลหรือแบบฟอร์มในเว็บไซต์",
    "thDetalji": "รายละเอียด",
    "porukaPretrage": "เลือกพารามิเตอร์แล้วคลิกค้นหาเพื่อดูตารางเดินรถ",
    "closeDetaljiModal": "ยังไม่ใช่!",
    "trajanje_voznje": "ระยะเวลาเดินทาง",
    "kolosjek": "รางรถไฟ",
    "slobodna_mjesta": "ที่นั่งว่าง",
    "katStanica": "สถานี",
    "katVozovi": "รถไฟ",
    "katIstorija": "ประวัติศาสตร์",
    "katOkolina": "บริเวณโดยรอบ",
    "mapaRuta": "เส้นทางบนแผนที่",
    "stanica_Пљевља": "พลเยฟลยา",
"stanica_Подгорица": "โพดโกริกา",
"stanica_Бар": "บาร์",
    "lokacija": "สถานที่",
  }
    },
    "vi": {
  translation: {
    "title": "Ga tàu Pljevlja",
    "naslov": "GA TÀU \"PLJEVLJA\" KHÔNG TỒN TẠI, ĐÂY CHỈ LÀ BÀI TẬP LẬP TRÌNH!",
    "podnaslov": "Chào mừng đến với trang chính thức!",
    "footer": "&copy; 20__ Ga tàu Pljevlja",
    "navNaslovna": "Trang chủ",
    "navKontakt": "Liên hệ",
    "navVozniRed": "Lịch trình",
    "navGalerija": "Thư viện ảnh",
    "navInformacije": "Thông tin",
    "navOpsteInformacije": "Thông tin chung",
    "navFAQ": "Câu hỏi thường gặp",
    "navIstorija": "Lịch sử",
    "p1": "Chào mừng đến với trang chính thức của ga tàu Pljevlja!",
    "p2": "Tại đây bạn sẽ tìm thấy mọi thông tin về lịch trình, liên hệ và thư viện ảnh.",
    "p3": "Để biết thêm thông tin, hãy chọn một mục trong menu.",
    "p4": "Cảm ơn bạn đã ghé thăm trang web của chúng tôi!",
    "p5": "Nếu bạn có câu hỏi hoặc góp ý, vui lòng liên hệ.",
    "p6": "Trân trọng,",
    "p7": "Ga tàu Pljevlja",
    "kontaktNaslov": "Liên hệ",
    "kontaktInfo": "Thông tin liên hệ",
    "adresa": "Địa chỉ: Ga tàu Pljevlja, Pljevlja, Montenegro",
    "telefon": "Điện thoại: +382 555666555",
    "email": "Email: info@zeljeznickastanicapljevlja.me",
    "posaljitePoruku": "Gửi tin nhắn",
    "lblIme": "Tên:",
    "lblPrezime": "Họ:",
    "lblEmail": "Email:",
    "lblPoruka": "Tin nhắn:",
    "btnPosalji": "Gửi",
    "ime": "Tên",
    "prezime": "Họ",
    "poruka": "Tin nhắn",
    "adresaLabel": "Địa chỉ:",
    "telefonLabel": "Điện thoại:",
    "emailLabel": "Email:",
    "radnoVremeLabel": "Giờ làm việc:",
    "radnoVremeVrednost": "07:00 – 20:00 (Thứ hai–Chủ nhật)",
    "galerijaNaslov": "Thư viện ảnh các ga tàu",
    "opis1": "Ga Podgorica (2013)",
    "opis2": "Ga Bar (2013)",
    "opis3": "Ga Bar (2019)",
    "opis4": "Ga Podgorica (2019)",
    "opis5": "Sân ga Bar",
    "alt1": "Ga Podgorica",
    "alt2": "Ga Bar",
    "alt3": "Ga Bar 2019",
    "alt4": "Ga Podgorica 2019",
    "alt5": "Sân ga Bar",
    "informacijeNaslov": "Thông tin",
    "nemaVozova": "Hiện không có chuyến tàu nào.",
    "pretrazi": "Tìm kiếm",
    "datum": "Ngày",
    "polazak": "Khởi hành",
    "dolazak": "Đến nơi",
    "od": "Từ",
    "ka": "Đến",
    "prevoznik": "Nhà vận chuyển",
    "tipKarte": "Loại vé",
    "rezervacija": "Đặt chỗ",
    "placanje": "Thanh toán",
    "student": "Giảm giá sinh viên",
    "penzioner": "Giảm giá người già",
    "cena": "Giá",
    "napomena": "Ghi chú",
    "lblOd": "Từ:",
    "lblKa": "Đến:",
    "lblDatum": "Ngày:",
    "btnPretrazi": "Tìm kiếm",
    "thDatum": "Ngày",
    "thPolazak": "Khởi hành",
    "thDolazak": "Đến nơi",
    "thOd": "Từ",
    "thKa": "Đến",
    "thPrevoznik": "Nhà vận chuyển",
    "thTipKarte": "Loại vé",
    "thRezervacija": "Đặt chỗ",
    "thPlacanje": "Thanh toán",
    "thStudent": "Giảm giá sinh viên",
    "thPenzioner": "Giảm giá người già",
    "thCena": "Giá",
    "thNapomena": "Ghi chú",
    "thSlobodnaMjesta": "Chỗ trống",
    "thRezervisanoMjesta": "Chỗ đã đặt",
    "thUkupnoMjesta": "Tổng số chỗ",
    "thCijenaKarte": "Giá vé",
    "thTipVoznje": "Loại hành trình",
    "thVoz": "Tàu",
    "thVozniRed": "Lịch trình",
    "thVozniRedDatum": "Ngày",
    "thVozniRedVrijeme": "Giờ",
    "thVozniRedPolazak": "Khởi hành",
    "thVozniRedDolazak": "Đến nơi",
    "thVozniRedOd": "Từ",
    "thVozniRedKa": "Đến",
    "thVozniRedPrevoznik": "Nhà vận chuyển",
    "thVozniRedTipKarte": "Loại vé",
    "thVozniRedRezervacija": "Đặt chỗ",
    "thVozniRedPlacanje": "Thanh toán",
    "thVozniRedStudent": "Giảm giá sinh viên",
    "thVozniRedPenzioner": "Giảm giá người già",
    "thVozniRedCena": "Giá",
    "thVozniRedNapomena": "Ghi chú",
    "placanje_online": "Thanh toán trực tuyến",
    "placanje_gotovina": "Thanh toán tiền mặt",
    "placanje_kartica": "Thanh toán bằng thẻ",
    "placanje_PayPal": "Thanh toán qua PayPal",
    "placanjeStripe": "Stripe",
    "placanjeOnline": "Thanh toán trực tuyến",
    "Pređи_na_plaćanje": "Chuyển đến thanh toán",
    "Kupi_kartu": "Mua vé",
    "Ipak_ne": "Chưa phải lúc này",
    "uplatnaForma": "Biểu mẫu thanh toán",
    "sql_modal": "Chọn phương thức thanh toán:",
    "Izaberite_način_plaćanja": "Chọn phương thức thanh toán:",
    "kupovinaNijeDostupna": "Không thể mua vé trực tuyến cho chuyến này. Vui lòng liên hệ ga để biết thêm thông tin.",
    "nijeIzabranPolazak": "Chưa chọn chuyến đi.",
    "nema_podataka": "Không có dữ liệu",
    "closeModal": "Chưa phải lúc này!",
    "broj_telefona": "Số điện thoại",
    "email_adresa": "Địa chỉ email",
    "adresa_stanice": "Địa chỉ ga",
    "radno_vrijeme": "Giờ làm việc",
    "radno_vrijeme_vrijednost": "07:00 – 20:00 (Thứ hai–Chủ nhật)",
    "brojSlobodnihMjesta": "Số chỗ trống",
    "detaljiPolaska": "Chi tiết chuyến đi",
    "naslovTab": "Lịch trình",
    "rezervacija_da": "Có",
    "rezervacija_ne": "Không",
    "footerZvanicniLinkovi": "Liên kết chính thức",
    "footerLinkZCG": "Đường sắt Montenegro",
    "footerLinkZICG": "Cơ sở hạ tầng đường sắt Montenegro",
    "footerLinkVlada": "Chính phủ Montenegro",
    "footerLinkOpština": "Thành phố Pljevlja",
    "footerLinkTOP": "Tổ chức du lịch Pljevlja",
    "footerLinkJUCKPV": "Trung tâm văn hóa Pljevlja",
    "footerDrustveneMreze": "Mạng xã hội",
    "footerFacebook": "Facebook",
    "footerInstagram": "Instagram",
    "footerTwitter": "Twitter",
    "footerQRNaslov": "Mã QR",
    "footerQROpis": "Quét mã QR để truy cập nhanh dịch vụ và thông tin của chúng tôi",
    "footerQRAlt": "Mã QR ga Pljevlja",
    "faqNaslovTab": "Câu hỏi thường gặp",
    "faqNaslov": "Câu hỏi thường gặp (FAQ)",
    "faqPitanje1": "Có thể mua vé trực tuyến không?",
    "faqOdgovor1": "Hiện tại chưa thể mua vé trực tuyến vì ga chưa được xây dựng.",
    "faqPitanje2": "Tôi có thể lấy thông tin chuyến đi ở đâu?",
    "faqOdgovor2": "Tất cả thông tin sẽ có trên trang web này khi ga đi vào hoạt động.",
    "faqPitanje3": "Làm sao để liên hệ với ga?",
    "faqOdgovor3": "Thông tin liên hệ sẽ được công bố sau khi xây dựng xong.",
    "faqPitanje4": "Có giảm giá cho sinh viên và người già không?",
    "faqOdgovor4": "Sẽ có giảm giá cho sinh viên và người già.",
    "istorijaNaslovTab": "Lịch sử",
    "istorijaNaslov": "Lịch sử ga Pljevlja",
    "istorijaTekst1": "Ga Pljevlja được quy hoạch là trung tâm giao thông quan trọng của khu vực.",
    "istorijaTekst2": "Ga sẽ giúp kết nối thành phố với các vùng khác trong nước và khu vực.",
    "istorijaTekst3": "Chi tiết về xây dựng, sức chứa và ngày khai trương sẽ được công bố sau khi dự án hoàn thành.",
    "Pravila_Privatnosti": "Chính sách bảo mật",
    "privatnostNaslov": "Ví dụ về chính sách bảo mật",
    "privatnostPodnaslov": "Chính sách bảo mật",
    "privatnostPrikupljanje": "Thu thập thông tin",
    "privatnostKorisćenje": "Sử dụng thông tin",
    "privatnostDijeljenje": "Chia sẻ thông tin",
    "privatnostSigurnost": "Bảo mật thông tin",
    "privatnostVasaPrava": "Quyền của bạn",
    "privatnostPromjene": "Thay đổi chính sách",
    "privatnostKontakt": "Liên hệ",
    "privatnostP1": "Chính sách này mô tả cách chúng tôi thu thập, sử dụng và chia sẻ thông tin của bạn khi sử dụng trang web.",
    "privatnostP2": "Chúng tôi thu thập thông tin bạn cung cấp khi đăng ký, nhận bản tin hoặc liên hệ qua biểu mẫu.",
    "privatnostP3": "Chúng tôi chỉ sử dụng thông tin của bạn cho mục đích bạn đã cung cấp.",
    "privatnostP4": "Chúng tôi không chia sẻ thông tin cá nhân của bạn với bên thứ ba trừ khi pháp luật yêu cầu.",
    "privatnostP5": "Chúng tôi thực hiện mọi biện pháp hợp lý để bảo vệ dữ liệu của bạn.",
    "privatnostP6": "Bạn có thể yêu cầu truy cập, chỉnh sửa hoặc xóa dữ liệu của mình bất cứ lúc nào.",
    "privatnostP7": "Chúng tôi có quyền cập nhật chính sách này định kỳ.",
    "privatnostP8": "Nếu bạn có câu hỏi, vui lòng liên hệ qua email hoặc biểu mẫu trên trang web.",
    "thDetalji": "Chi tiết",
    "porukaPretrage": "Chọn tham số và nhấn Tìm kiếm để xem lịch trình.",
    "closeDetaljiModal": "Chưa phải lúc này!",
    "trajanje_voznje": "Thời gian hành trình",
    "kolosjek": "Đường ray",
    "slobodna_mjesta": "Chỗ trống",
    "katStanica": "Ga",
    "katVozovi": "Tàu",
    "katIstorija": "Lịch sử",
    "katOkolina": "Khu vực xung quanh",
    "mapaRuta": "Tuyến đường trên bản đồ",
    "stanica_Пљевља": "Pljevlja",
"stanica_Подгорица": "Podgorica",
"stanica_Бар": "Bar",
    "lokacija": "Vị trí",
  }
    },
  
};

window.extraResources = extraResources;
//export default extraResources;